# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servaiman.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servaiman.proto',
  package='servaiman_proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0fservaiman.proto\x12\x0fservaiman_proto\"\x19\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x17\n\x07Request\x12\x0c\n\x04size\x18\x01 \x01(\x05\",\n\nTwoDMatrix\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x01\x42\x02\x10\x01\"!\n\x04Meta\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x05\x12\x0b\n\x03gnb\x18\x02 \x01(\x05\x32\x9f\x04\n\tServaiman\x12<\n\x08PostMeta\x12\x15.servaiman_proto.Meta\x1a\x17.servaiman_proto.Status\"\x00\x12\x42\n\x06PostCn\x12\x1b.servaiman_proto.TwoDMatrix\x1a\x17.servaiman_proto.Status\"\x00(\x01\x12\x42\n\x06PostAb\x12\x1b.servaiman_proto.TwoDMatrix\x1a\x17.servaiman_proto.Status\"\x00(\x01\x12\x42\n\x06PostCf\x12\x1b.servaiman_proto.TwoDMatrix\x1a\x17.servaiman_proto.Status\"\x00(\x01\x12<\n\x07GetMeta\x12\x18.servaiman_proto.Request\x1a\x15.servaiman_proto.Meta\"\x00\x12\x42\n\x05GetCn\x12\x18.servaiman_proto.Request\x1a\x1b.servaiman_proto.TwoDMatrix\"\x00\x30\x01\x12\x42\n\x05GetAb\x12\x18.servaiman_proto.Request\x1a\x1b.servaiman_proto.TwoDMatrix\"\x00\x30\x01\x12\x42\n\x05GetCf\x12\x18.servaiman_proto.Request\x1a\x1b.servaiman_proto.TwoDMatrix\"\x00\x30\x01\x62\x06proto3')
)




_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='servaiman_proto.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='servaiman_proto.Status.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=61,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='servaiman_proto.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='servaiman_proto.Request.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=86,
)


_TWODMATRIX = _descriptor.Descriptor(
  name='TwoDMatrix',
  full_name='servaiman_proto.TwoDMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='servaiman_proto.TwoDMatrix.rows', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='servaiman_proto.TwoDMatrix.data', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=132,
)


_META = _descriptor.Descriptor(
  name='Meta',
  full_name='servaiman_proto.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dims', full_name='servaiman_proto.Meta.dims', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gnb', full_name='servaiman_proto.Meta.gnb', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['TwoDMatrix'] = _TWODMATRIX
DESCRIPTOR.message_types_by_name['Meta'] = _META
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'servaiman_pb2'
  # @@protoc_insertion_point(class_scope:servaiman_proto.Status)
  ))
_sym_db.RegisterMessage(Status)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'servaiman_pb2'
  # @@protoc_insertion_point(class_scope:servaiman_proto.Request)
  ))
_sym_db.RegisterMessage(Request)

TwoDMatrix = _reflection.GeneratedProtocolMessageType('TwoDMatrix', (_message.Message,), dict(
  DESCRIPTOR = _TWODMATRIX,
  __module__ = 'servaiman_pb2'
  # @@protoc_insertion_point(class_scope:servaiman_proto.TwoDMatrix)
  ))
_sym_db.RegisterMessage(TwoDMatrix)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'servaiman_pb2'
  # @@protoc_insertion_point(class_scope:servaiman_proto.Meta)
  ))
_sym_db.RegisterMessage(Meta)


_TWODMATRIX.fields_by_name['data'].has_options = True
_TWODMATRIX.fields_by_name['data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))

_SERVAIMAN = _descriptor.ServiceDescriptor(
  name='Servaiman',
  full_name='servaiman_proto.Servaiman',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=170,
  serialized_end=713,
  methods=[
  _descriptor.MethodDescriptor(
    name='PostMeta',
    full_name='servaiman_proto.Servaiman.PostMeta',
    index=0,
    containing_service=None,
    input_type=_META,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PostCn',
    full_name='servaiman_proto.Servaiman.PostCn',
    index=1,
    containing_service=None,
    input_type=_TWODMATRIX,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PostAb',
    full_name='servaiman_proto.Servaiman.PostAb',
    index=2,
    containing_service=None,
    input_type=_TWODMATRIX,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PostCf',
    full_name='servaiman_proto.Servaiman.PostCf',
    index=3,
    containing_service=None,
    input_type=_TWODMATRIX,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMeta',
    full_name='servaiman_proto.Servaiman.GetMeta',
    index=4,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_META,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCn',
    full_name='servaiman_proto.Servaiman.GetCn',
    index=5,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_TWODMATRIX,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAb',
    full_name='servaiman_proto.Servaiman.GetAb',
    index=6,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_TWODMATRIX,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCf',
    full_name='servaiman_proto.Servaiman.GetCf',
    index=7,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_TWODMATRIX,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVAIMAN)

DESCRIPTOR.services_by_name['Servaiman'] = _SERVAIMAN

# @@protoc_insertion_point(module_scope)
